packages:
  - packages/*
  - apps/*
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@anthropic-ai/claude-agent-sdk-darwin-arm64@0.3.204'
  - '@anthropic-ai/claude-agent-sdk-darwin-x64@0.3.204'
  - '@anthropic-ai/claude-agent-sdk-linux-arm64-musl@0.3.204'
  - '@anthropic-ai/claude-agent-sdk-linux-arm64@0.3.204'
  - '@anthropic-ai/claude-agent-sdk-linux-x64-musl@0.3.204'
  - '@anthropic-ai/claude-agent-sdk-linux-x64@0.3.204'
  - '@anthropic-ai/claude-agent-sdk-win32-arm64@0.3.204'
  - '@anthropic-ai/claude-agent-sdk-win32-x64@0.3.204'
  - '@anthropic-ai/claude-agent-sdk@0.3.204'
  - '@expo/cli@57.0.6'
  - '@expo/config-plugins@57.0.3'
  - '@expo/config@57.0.3'
  - '@expo/fingerprint@0.20.3'
  - '@expo/inline-modules@0.1.2'
  - '@expo/prebuild-config@57.0.5'
  - '@expo/router-server@57.0.2'
  - babel-preset-expo@57.0.2
  - expo-modules-autolinking@57.0.5
  - expo-modules-core@57.0.3
  - expo-modules-jsi@57.0.1
  - expo@57.0.4
  - expo-camera@57.0.1
patchedDependencies:
  expo-modules-jsi@57.0.1: patches/expo-modules-jsi@57.0.1.patch
